services:
  user-service-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_service_db
    ports:
      - "5432:5432"
    volumes:
      - user-service-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  user-service:
    build: ./services/user-service
    ports:
      - "50051:50051"
    depends_on:
      user-service-db:
        condition: service_healthy
    environment:
      - DB_SOURCE=postgres://postgres:postgres@user-service-db:5432/user_service_db?sslmode=disable
    networks:
      - ecommerce-network

volumes:
  user-service-db-data:

networks:
  ecommerce-network:
  
